version: "3"
services:
  mysql-kuber:
    image: mysql:5.7
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: none
    ports:
      - "3306:3306"
    networks:
      - users-network
    environment:
      - MYSQL_ROOT_PASSWORD=temporal1
    volumes:
      - mysql-data:/var/lib/mysql
  kubernetes-summit-app:
    image: arknot/summit-kubernetes:0.0.20
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - users-network
    environment:
      - MYSQL_USER=user_test
      - MYSQL_PASSWORD=user_pass
      - MYSQL_DATABASE=summit
      - MYSQL_TEST_PORT_3306_TCP_ADDR=mysql-kuber
      - MYSQL_TEST_PORT_3306_TCP_PORT=3306
      - PORT=3000

volumes:
  mysql-data:
    external:
      name: mysql-data
networks:
  users-network: